/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoMoverPlugin
});
module.exports = __toCommonJS(main_exports);

// Settings/Settings.ts
var DEFAULT_SETTINGS = {
  moveOnOpen: true,
  moveOnSave: true,
  moveOnClose: false,
  moveOnCreate: false,
  movingRules: []
};

// Models/MovingRule.ts
var MovingRule = class {
  constructor(regex, folder) {
    this.regex = regex || "";
    this.folder = folder || "";
  }
};

// Settings/SettingsTab.ts
var obsidian = __toESM(require("obsidian"));
var SettingsTab = class extends obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new obsidian.Setting(containerEl).setName("Automatic moving").setHeading();
    new obsidian.Setting(containerEl).setName("Move on open").setDesc("Should the file be moved when it is opened?").addToggle(
      (cb) => cb.setValue(this.plugin.settings.moveOnOpen).onChange(async (value) => {
        this.plugin.settings.moveOnOpen = value;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    new obsidian.Setting(containerEl).setName("Manually move").setDesc(
      "Execute the command to go through your notes and move them according to the rules specified below."
    ).addButton((button) => {
      button.setButtonText("Move files");
      button.onClick(async () => {
        this.plugin.goThroughAllFiles();
      });
    });
    const tutorialContainer = containerEl.createDiv({
      cls: "moving_rules_container"
    });
    const headerSetting = new obsidian.Setting(tutorialContainer).setName("Tutorial").setHeading();
    const description = tutorialContainer.createDiv();
    description.createSpan({
      text: "This plugin allows you to move files to a specified folder based on the file name."
    });
    description.createEl("br", {});
    description.createSpan({
      text: "If you have multiple rules referencing the same file, the first rule will be applied."
    });
    description.createEl("br", {});
    description.createSpan({
      text: "Usage of regex groups is supported. To use them in the folder name, use $1, $2, etc. to reference the group."
    });
    description.createEl("br", {});
    description.createEl("br", {});
    description.createSpan({ text: "Examples: ", cls: "rule_title" });
    description.createEl("br", {});
    description.createSpan({
      text: "To move files containing 'Scroll' to a folder named 'Scrolls': "
    });
    const example1 = description.createDiv({ cls: "rule margig_right" });
    example1.createSpan({ text: "Scroll", cls: "rule_title" });
    example1.createSpan({ text: "Scrolls", cls: "rule_title" });
    description.createSpan({
      text: "To move files containing the word 'Scroll' and a number to space -> to a folder named 'Scrolls' under the subfolder of the scroll number: "
    });
    const example2 = description.createDiv({ cls: "rule margig_right" });
    example2.createSpan({ text: "Scroll (\\d+)", cls: "rule_title" });
    example2.createSpan({ text: "Scrolls/$1", cls: "rule_title" });
    const movingRulesContainer = containerEl.createDiv({
      cls: "moving_rules_container"
    });
    new obsidian.Setting(movingRulesContainer).setName("Moving rules").setHeading();
    const ruleList = movingRulesContainer.createDiv({ cls: "rule_list" });
    const ruleHeader = ruleList.createDiv({ cls: "rule margig_right" });
    ruleHeader.createEl("p", {
      text: "Search criteria (string or regex)",
      cls: "rule_title"
    });
    ruleHeader.createEl("p", {
      text: "Folder (string that can contain regex groups)",
      cls: "rule_title"
    });
    const addButton = ruleHeader.createEl("button", {
      text: "+",
      cls: "rule_button"
    });
    addButton.addEventListener("click", () => {
      this.plugin.settings.movingRules.push(new MovingRule());
      this.display();
    });
    for (const rule of this.plugin.settings.movingRules) {
      const child = ruleList.createDiv({ cls: "rule" });
      child.createEl("input", {
        value: rule.regex,
        cls: "rule_input"
      }).onchange = (e) => {
        rule.regex = e.target.value;
        this.plugin.settings.movingRules.map((r) => r === rule ? rule : r);
        this.plugin.saveData(this.plugin.settings);
      };
      child.createEl("input", {
        value: rule.folder,
        cls: "rule_input"
      }).onchange = (e) => {
        rule.folder = e.target.value;
        this.plugin.settings.movingRules.map((r) => r === rule ? rule : r);
        this.plugin.saveData(this.plugin.settings);
      };
      const duplicateButton = child.createEl("button", {
        text: "\u2FFB",
        cls: "rule_button rule_button_duplicate"
      });
      duplicateButton.addEventListener("click", () => {
        this.plugin.settings.movingRules.push(
          new MovingRule(rule.regex, rule.folder)
        );
        this.display();
      });
      const deleteButton = child.createEl("button", {
        text: "x",
        cls: "rule_button rule_button_remove"
      });
      deleteButton.addEventListener("click", () => {
        this.plugin.settings.movingRules = this.plugin.settings.movingRules.filter((r) => r !== rule);
        this.display();
      });
    }
  }
};

// Utils/MovingUtil.ts
var obsidian2 = __toESM(require("obsidian"));
var MovingUtil = class {
  constructor() {
  }
  static getInstance() {
    if (!MovingUtil.instance) {
      MovingUtil.instance = new MovingUtil();
    }
    return MovingUtil.instance;
  }
  init(app) {
    this.app = app;
  }
  /**
   * Checks if the path is a file
   *
   * @param path - Path to be checked
   * @returns boolean
   */
  isFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    return file instanceof obsidian2.TFile;
  }
  /**
   * Checks if the path is a folder
   *
   * @param path - Path to be checked
   * @returns boolean
   */
  isFolder(path) {
    return this.app.vault.getAbstractFileByPath(path) instanceof obsidian2.TFolder;
  }
  /**
   * Moves the file to the destination path
   *
   * @param file - File to be moved
   * @param newPath - Destination path
   * @returns void
   */
  moveFile(file, newPath) {
    if (this.isFolder(newPath)) {
      this.app.vault.rename(file, `${newPath}/${file.name}`);
    } else {
      new obsidian2.Notice(
        `Invalid destination path
${newPath} is not a folder!
Creating requested folder.`,
        5e3
      );
      console.error(
        `Invalid destination path
${newPath} is not a folder!
Creating requested folder.`
      );
      this.createMissingFolders(newPath).then(() => {
        this.app.vault.rename(file, `${newPath}/${file.name}`);
      });
    }
  }
  /**
   * Moves the folder to the destination path
   *
   * @param folder - Folder to be moved
   * @param newPath - Destination path
   * @returns void
   */
  moveFolder(folder, newPath) {
    if (this.isFolder(newPath)) {
      this.app.vault.rename(folder, `${newPath}/${folder.name}`);
    } else {
      new obsidian2.Notice(
        `Invalid destination path
${newPath} is not a folder!`,
        5e3
      );
      console.error(`Invalid destination path
${newPath} is not a folder!`);
    }
  }
  /**
   * Creates folder in destination path if it does not exist already
   *
   * @param path - Path of the folder to be created
   * @returns Created folder or null if folder already exists
   */
  createFolder(path) {
    if (!this.isFolder(path)) {
      this.app.vault.createFolder(path).then((folder) => {
        return folder;
      });
    } else {
      new obsidian2.Notice("Folder already exists", 5e3);
      console.error("Folder already exists");
    }
    return null;
  }
  /**
   * Splits the path into an array of strings
   *
   * @param path - Path to be split
   * @returns string[]
   */
  splitPath(path) {
    return path.split("/");
  }
  /**
   * Create missing folders in the path
   *
   * @param path - Path to be checked
   * @returns void
   */
  async createMissingFolders(path) {
    const splitPath = this.splitPath(path);
    let currentPath = "";
    for (const folder of splitPath) {
      currentPath += folder;
      if (!this.isFolder(currentPath)) {
        await this.app.vault.createFolder(path);
      }
      currentPath += "/";
    }
    if (this.isFolder(path)) {
      return true;
    }
    return false;
  }
};
var movingUtil = MovingUtil.getInstance();
var MovingUtil_default = movingUtil;

// Utils/RuleMatcherUtil.ts
var RuleMatcherUtil = class {
  constructor() {
  }
  static getInstance() {
    if (!RuleMatcherUtil.instance) {
      RuleMatcherUtil.instance = new RuleMatcherUtil();
    }
    return RuleMatcherUtil.instance;
  }
  /**
   * Returns the first rule that matches the file
   * If no rule matches, returns null
   *
   * @param file
   * @param rules
   * @returns MovingRule | null
   */
  getMatchingRule(file, rules) {
    for (const rule of rules) {
      if (rule.regex == null || rule.regex === "") {
        console.error("Rule does not have a regex: ", rule);
        continue;
      }
      if (!this.isValidRegex(rule.regex)) {
        console.error("Rule has an invalid regex: ", rule);
        continue;
      }
      if (file.name.match(rule.regex)) {
        return rule;
      }
    }
    return null;
  }
  /**
   * Returns the regex groups of the file that match the rule
   * If no groups match, returns an empty array
   *
   * @param file
   * @param rule
   * @returns string[]
   */
  getGroupMatches(file, rule) {
    const matches = file.name.match(rule.regex);
    return matches;
  }
  /**
   * Checks if the regex pattern is valid
   * Meaning, syntax errors are caught, but not logical errors
   *
   * @param pattern
   * @returns boolean
   */
  isValidRegex(pattern) {
    try {
      new RegExp(pattern);
      return true;
    } catch (e) {
      if (e instanceof SyntaxError) {
        console.error(`Invalid regex pattern: ${e.message}`);
      }
      return false;
    }
  }
  /**
   * Constructs the final destination path from the matched groups
   * The path is constructed by replacing the $1, $2, $3, etc. with the matched groups
   *
   * @param rule
   * @param matches
   */
  constructFinalDesinationPath(rule, matches) {
    var _a;
    let folderPath = rule.folder;
    const unnamedGroups = this.getUnnamedGroups(rule.regex);
    for (let i = 0; i < unnamedGroups.length; i++) {
      folderPath = folderPath.replace(`$${i + 1}`, (_a = matches[i + 1]) != null ? _a : "");
    }
    return folderPath;
  }
  /**
   * Is regex grouped
   * Groups are defined by (...) and used with $1, $2, $3, etc.
   *
   * @param rule
   * @returns boolean
   */
  isRegexGrouped(rule) {
    return this.doesDestinationUseGroups(rule) && this.getUnnamedGroups(rule.regex) != null;
  }
  /**
   * Returns the unnamed groups in the regex pattern
   *
   * @param pattern
   * @returns RegExpMatchArray | null
   */
  getUnnamedGroups(pattern) {
    return pattern.match(/\(/g);
  }
  /**
   * Does destination use groups
   * Groups are defined by $1, $2, $3, etc.
   *
   * @param rule
   * @returns boolean
   */
  doesDestinationUseGroups(rule) {
    return /\$\d/.test(rule.folder);
  }
};
var ruleMatcherUtil = RuleMatcherUtil.getInstance();
var RuleMatcherUtil_default = ruleMatcherUtil;

// main.ts
var obsidian3 = __toESM(require("obsidian"));
var AutoMoverPlugin = class extends obsidian3.Plugin {
  async onload() {
    MovingUtil_default.init(this.app);
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    this.addSettingTab(new SettingsTab(this.app, this));
    if (this.checkIfMovingTriggersAreEnabled() && this.checkIfThereAreRulesToApply() && this.checkIfRulesAreValid()) {
      if (this.settings.moveOnOpen) {
        this.registerEvent(
          this.app.workspace.on("file-open", (file) => {
            this.matchAndMoveFile(file);
          })
        );
      }
    }
  }
  /**
   * Opens all files in the repository so that the even "file-open" is triggered
   *
   * @returns void
   */
  goThroughAllFiles() {
    const files = this.app.vault.getFiles();
    for (const file of files) {
      this.matchAndMoveFile(file);
    }
    new obsidian3.Notice("All files moved!", 5e3);
  }
  /**
   * Matches the file to the rule and moves it to the destination folder
   *
   * @param file - File to be matched and moved
   * @returns void
   */
  matchAndMoveFile(file) {
    if (file == null || file.path == null)
      return;
    const rule = RuleMatcherUtil_default.getMatchingRule(
      file,
      this.settings.movingRules
    );
    if (rule == null || rule.folder == null)
      return;
    if (RuleMatcherUtil_default.isRegexGrouped(rule)) {
      const matches = RuleMatcherUtil_default.getGroupMatches(file, rule);
      const finalDestinationPath = RuleMatcherUtil_default.constructFinalDesinationPath(
        rule,
        matches
      );
      MovingUtil_default.moveFile(file, finalDestinationPath);
    } else {
      MovingUtil_default.moveFile(file, rule.folder);
    }
  }
  async asyncloadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async onunload() {
  }
  /**
   * No point in doing anything if there is no trigger set which will cause you to move the files
   * @returns boolean
   */
  checkIfMovingTriggersAreEnabled() {
    return this.settings.moveOnClose || this.settings.moveOnCreate || this.settings.moveOnOpen || this.settings.moveOnSave;
  }
  /**
   * If there are no rules to apply, then there is no point in checking for them
   * @returns boolean
   */
  checkIfThereAreRulesToApply() {
    return this.settings.movingRules.length > 0;
  }
  /**
   * Superficail check if the rules are valid
   * @returns boolean
   */
  checkIfRulesAreValid() {
    return this.settings.movingRules.every(
      (rule) => rule.regex !== "" && rule.folder !== ""
    );
  }
};


/* nosourcemap */